# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ayarlar.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import webbrowser

class Ui_ayarlar(object):
    def setupUi(self, ayarlar):
        ayarlar.setObjectName("ayarlar")
        ayarlar.resize(517, 218)
        font = QtGui.QFont()
        font.setPointSize(8)
        ayarlar.setFont(font)
        ayarlar.setStyleSheet("background-color: rgb(197, 197, 197);")
        self.commandLinkButton = QtWidgets.QCommandLinkButton(ayarlar)
        self.commandLinkButton.setEnabled(True)
        self.commandLinkButton.setGeometry(QtCore.QRect(10, 190, 96, 31))
        self.commandLinkButton.setStyleSheet("color: rgb(0, 0, 255);")
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.commandLinkButton.clicked.connect(self.ac)
        self.pushButton = QtWidgets.QPushButton(ayarlar)
        self.pushButton.setGeometry(QtCore.QRect(50, 140, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.062, y1:0, x2:0.045, y2:0.954545, stop:0 rgba(203, 203, 203, 255), stop:0.316384 rgba(187, 187, 187, 255), stop:0.615819 rgba(137, 137, 137, 255), stop:0.694915 rgba(126, 126, 126, 255));")
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(ayarlar)
        self.label.setEnabled(False)
        self.label.setGeometry(QtCore.QRect(15, 9, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(ayarlar)
        self.line.setGeometry(QtCore.QRect(7, 21, 12, 169))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_2 = QtWidgets.QLabel(ayarlar)
        self.label_2.setGeometry(QtCore.QRect(19, 40, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(ayarlar)
        self.lineEdit.setGeometry(QtCore.QRect(120, 40, 113, 20))
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(ayarlar)
        self.label_3.setGeometry(QtCore.QRect(18, 71, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(ayarlar)
        self.lineEdit_2.setGeometry(QtCore.QRect(120, 71, 113, 20))
        self.lineEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_4 = QtWidgets.QLabel(ayarlar)
        self.label_4.setGeometry(QtCore.QRect(18, 103, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEdit_3 = QtWidgets.QLineEdit(ayarlar)
        self.lineEdit_3.setGeometry(QtCore.QRect(120, 101, 113, 20))
        self.lineEdit_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.line_2 = QtWidgets.QFrame(ayarlar)
        self.line_2.setGeometry(QtCore.QRect(103, 20, 143, 3))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(ayarlar)
        self.line_3.setGeometry(QtCore.QRect(247, 20, 3, 171))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(ayarlar)
        self.line_4.setGeometry(QtCore.QRect(10, 190, 238, 3))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(ayarlar)
        self.line_5.setGeometry(QtCore.QRect(270, 20, 3, 171))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(ayarlar)
        self.line_6.setGeometry(QtCore.QRect(337, 20, 166, 4))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.label_5 = QtWidgets.QLabel(ayarlar)
        self.label_5.setEnabled(False)
        self.label_5.setGeometry(QtCore.QRect(271, 7, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.line_7 = QtWidgets.QFrame(ayarlar)
        self.line_7.setGeometry(QtCore.QRect(500, 20, 3, 168))
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(ayarlar)
        self.line_8.setGeometry(QtCore.QRect(270, 190, 230, 3))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.label_6 = QtWidgets.QLabel(ayarlar)
        self.label_6.setGeometry(QtCore.QRect(280, 40, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.lineEdit_4 = QtWidgets.QLineEdit(ayarlar)
        self.lineEdit_4.setGeometry(QtCore.QRect(370, 40, 113, 20))
        self.lineEdit_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(ayarlar)
        self.lineEdit_5.setGeometry(QtCore.QRect(370, 70, 113, 20))
        self.lineEdit_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_7 = QtWidgets.QLabel(ayarlar)
        self.label_7.setGeometry(QtCore.QRect(281, 75, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(ayarlar)
        self.label_8.setGeometry(QtCore.QRect(280, 106, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.lineEdit_6 = QtWidgets.QLineEdit(ayarlar)
        self.lineEdit_6.setGeometry(QtCore.QRect(370, 100, 113, 20))
        self.lineEdit_6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.pushButton_2 = QtWidgets.QPushButton(ayarlar)
        self.pushButton_2.setGeometry(QtCore.QRect(330, 140, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.062, y1:0, x2:0.045, y2:0.954545, stop:0 rgba(203, 203, 203, 255), stop:0.316384 rgba(187, 187, 187, 255), stop:0.615819 rgba(137, 137, 137, 255), stop:0.694915 rgba(126, 126, 126, 255));")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/Treetog-I-Floppy-Small.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(ayarlar)
        QtCore.QMetaObject.connectSlotsByName(ayarlar)

    def retranslateUi(self, ayarlar):
        _translate = QtCore.QCoreApplication.translate
        ayarlar.setWindowTitle(_translate("ayarlar", "AYARLAR"))
        self.commandLinkButton.setText(_translate("ayarlar", "İLETİŞİM"))
        self.pushButton.setText(_translate("ayarlar", "Parolayı Değiştir"))
        self.label.setText(_translate("ayarlar", "Hesap Bilgileri"))
        self.label_2.setText(_translate("ayarlar", "Eski Parola:"))
        self.label_3.setText(_translate("ayarlar", "Yeni Parola:"))
        self.label_4.setText(_translate("ayarlar", "Güvenlik PIN:"))
        self.label_5.setText(_translate("ayarlar", "Yeni Hesap"))
        self.label_6.setText(_translate("ayarlar", "Kullanıcı Adı:"))
        self.label_7.setText(_translate("ayarlar", "Parola:"))
        self.label_8.setText(_translate("ayarlar", "Güvenlik PIN:"))
        self.pushButton_2.setText(_translate("ayarlar", "Kaydet"))
    def ac(self):
        webbrowser.open("https://github.com/ebuubeyde")
import kaydet_icon

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ayarlar = QtWidgets.QWidget()
    ui = Ui_ayarlar()
    ui.setupUi(ayarlar)
    ayarlar.show()
    sys.exit(app.exec_())

